### ISSUE TITLE
Range "dot" looks off

### ISSUE THREAD

**Issue by johnswords** [turnto/carhartt-css#11]
<img width="242" alt="screen shot 2016-05-13 at 4 14 24 pm" src="https://cloud.githubusercontent.com/assets/7141517/15260973/bf0eda84-1927-11e6-9d9e-a442364488da.png">

**Comment by energy7** [comment]
@johnswords What's a page where I can see this? I thought you said on shoes but I don't see it.

**Comment by energy7** [comment]
@johnswords Found one. http://test-staging.carhartt.com/products/carhartt-men-outerwear/Shoreline-Pant-B216

The upper dot says margin-left: 81.49999785423279%; — is the JS trying to lock the dot into 1 of 5 positions, or is it just positioned according to the mathematically calculated percentage? 

I think it's an image error, where the previous dot had to overlap the bg image a bit... 
![screen shot 2016-05-18 at 5 51 52 pm](https://cloud.githubusercontent.com/assets/395013/15376161/4ea8301c-1d21-11e6-8c08-9b97a6199dfe.png)

I'm widening the bg image a bit...

**Comment by johnswords** [comment]
@rbonsall-turnto says "it’s trying to lock it into one of the 5 positions.  Not sure why the crazy number.  It calculates the % based on the position it is supposed to be then, adjusts a little for the width of the dot.  If their dot is a different size, that could make it be off a little"

**Comment by johnswords** [comment]
@energy7 does russ' response help you?

**Comment by energy7** [comment]
Hopefully it's now a non-issue, they agreed to change the background image to 
![image](https://cloud.githubusercontent.com/assets/395013/15543954/e33e928c-2264-11e6-9a51-1cc730702b6d.png)
