### ISSUE TITLE
Request for stars instead of the bars for rating dimensions

### ISSUE THREAD

**Issue by johnswords** [turnto/carhartt-css#12]
For Reviews, they would like to keep star ratings (which they havewith BV) for the following sub-dimensions:
-Appearance
-Durability
-Quality
-Comfort

That would impact the display and the Review form.

![Their BV implementation](https://cloud.githubusercontent.com/assets/7141517/15261248/3be6a25c-1929-11e6-9ebf-7b18388b2f7d.png)

**Comment by johnswords** [comment]
This sounds like something that might be very hard to do and keep consistent.  It would have to reference another sprite sheet right?

**Comment by energy7** [comment]
@johnswords The stars are taller than the bars, so we can't just replace the bars in the sprite sheet. We'd have to change the CSS for each of the 10 states of the subdimensions so that the background position and height correspond to the stars instead of the bars.

**Comment by energy7** [comment]
It seems to work ok? 
![screen shot 2016-05-18 at 5 04 18 pm](https://cloud.githubusercontent.com/assets/395013/15374921/a16dc2e6-1d1a-11e6-86c7-bbc8cf2dc755.png)
