### ISSUE TITLE
Instant Answer Search Results and Drill Down

### ISSUE THREAD

**Issue by johnswords** [turnto/carhartt-css#5]
Click into the search box on this page:
http://test-staging.carhartt.com/products/Force-%23153-6-Inch-Brown-Waterproof-Work-Boot-CMA6346

Type in "good boot" and you'll get instant answer results.  

1. The byline under the title is a bit hard to read in grey.  ("Review for XY") Maybe its ok? 

<img width="1218" alt="screen shot 2016-05-05 at 4 12 52 pm" src="https://cloud.githubusercontent.com/assets/7141517/15055895/0b3e9e40-12dd-11e6-9cde-1c7ba56211bd.png">

2. When you click on one of the reviews in the results list and go to the detail / drill down, the Back button needs padding (and maybe resizing, not sure) to match the other buttons.  

 <img width="1230" alt="screen shot 2016-05-05 at 4 13 03 pm" src="https://cloud.githubusercontent.com/assets/7141517/15055846/b8fbe994-12dc-11e6-9a44-1a8cac990136.png">

**Comment by energy7** [comment]
Fixed
