### ISSUE TITLE
Ratings (e.g. "4/5") on individual Reviews in the listing see like they are under any sort of alignment with the graphics to their left

### ISSUE THREAD

**Issue by johnswords** [turnto/carhartt-css#6]
<img width="216" alt="screen shot 2016-05-05 at 4 12 09 pm" src="https://cloud.githubusercontent.com/assets/7141517/15055954/42cd1350-12dd-11e6-8789-8503755ead8a.png">

**Comment by energy7** [comment]
Fixed
